### ISSUE TITLE
peak finder

### ISSUE THREAD

**Issue by JulianKimmig** [Linkdlab/funcnodes_span#23]
peakfinder on unsmoothed data works not as expected.
this is the corresponding data:
[data.csv](https://github.com/user-attachments/files/17001364/data.csv)

![grafik](https://github.com/user-attachments/assets/c50c47e7-52b8-443f-a869-05c84636f639)

**Comment by kouroshrezaei** [comment]
There was no issue from the algorithm in this case. The input data was too noisy. However the plotting of the peaks is updated and can properly display the ranges of each peak.

![image](https://github.com/user-attachments/assets/25fdc915-dd11-4fa0-9f4f-294b477070c6)

![image](https://github.com/user-attachments/assets/68dafbbd-d674-4b74-92d7-9ac9e28f941d)

![image](https://github.com/user-attachments/assets/18089b48-aed2-4fcf-be41-391940a2681d)

**Comment by JulianKimmig** [comment]
And the initial unexpected peak position was due to setting a width parameter, which selected only a broad noise induced peak at the highlighted position. It was at the side of the peak, because with the high derivative the signal noise does not create a lot of small peaks there.
